### ISSUE TITLE
Missing PostgresEngine

### ISSUE THREAD

**Issue by CriztianiX** [josegonzalez/cakephp-queuesadilla#11]
https://github.com/josegonzalez/cakephp-queuesadilla/blob/master/src/Queue/Queue.php#L73

Should be contain:

`'postgres' => 'josegonzalez\Queuesadilla\Engine\PostgresEngine'`

**Comment by josegonzalez** [comment]
Pull requests welcome.

**Comment by CriztianiX** [comment]
https://github.com/josegonzalez/cakephp-queuesadilla/pull/12

**Comment by josegonzalez** [comment]
Closing as there is a pull request open.
