### ISSUE TITLE
queue Shell param not passed to worker

### ISSUE THREAD

**Issue by robertscherer** [josegonzalez/cakephp-queuesadilla#2]
I'm not sure if this is a bug or a misunderstanding on my part.

I have configured a `default` config using the `MysqlEngine` and am running the shell using the following command:

    bin/cake queuesadilla --config default --queue email

The Jobs queued for the `email` queue are not performed. Is this a wanted behavior?

Thanks

**Comment by josegonzalez** [comment]
It should be overriding it [here](https://github.com/josegonzalez/cakephp-queuesadilla/blob/master/src/Shell/QueuesadillaShell.php#L25). What is the output of the logger?

**Comment by robertscherer** [comment]
The output of the logger is just "No job".

I have debugged it and found that the `queue` param is `default` in the Worker instance (this is a protected property called `$queue` in `josegonzalez\Queuesadilla\Worker\Base`.

I think we just need to pass the parameter to the Worker's constructor in `QueuesadillaShell::getWorker()`. 

I'm not clear about the architecture related to the fact that both the engine and the worker  would need the `queue` param.

**Comment by josegonzalez** [comment]
You can override the engine's queue when using an engine, so this makes sense. I just verified the issue and will push a fix out.

**Comment by josegonzalez** [comment]
Closed by https://github.com/josegonzalez/cakephp-queuesadilla/commit/bb95ca11a6ea107bf66496a0ed3c9ee86593476e

**Comment by josegonzalez** [comment]
Released in https://github.com/josegonzalez/cakephp-queuesadilla/releases/tag/0.3.3
