### ISSUE TITLE
Queue::reset() doesn't reset $_queuers

### ISSUE THREAD

**Issue by asaliev** [josegonzalez/cakephp-queuesadilla#25]
I've been doing some work around the `Queue` class, and while testing I've encountered an issue that the private property $_queuers doesn't get reset in the `reset()` method, giving me unwanted results across different phpunit test functions.

Is there a particular reason for not resetting queuers, or it's just something that's been missed?

Referenced function: https://github.com/josegonzalez/cakephp-queuesadilla/blob/5e4f733efbec81c341db13b2adea1fcf4320d798/src/Queue/Queue.php#L181-L186

**Comment by josegonzalez** [comment]
Nope, but pull requests welcome :)

**Comment by asaliev** [comment]
@josegonzalez gotcha ;)
