### ISSUE TITLE
Use Datasource Configuration for Queuesadilla

### ISSUE THREAD

**Issue by robertscherer** [josegonzalez/cakephp-queuesadilla#3]
When using the Plugin in a standard CakePHP application with a PDO-based engine, it practically forces you to configure the database credentials twice in the app's configuration.

I think it'd be a good idea to re-use the Datasource configs for configuration DB access for queuesadilla, which would be especially useful when writing unit tests.

@josegonzalez Do you think this brings inconsistency to configuration when using non-PDO-based engines?

**Comment by josegonzalez** [comment]
Probably, but the key naming should be the same for all of them, so I don't think it's an issue.

**Comment by josegonzalez** [comment]
One thing I do is use environment variables for configuring queuesadilla, so it's really only one key that I am duplicating.

**Comment by josegonzalez** [comment]
Yeah I'm going to close this. I don't think it makes sense, given the ability to use the `url` key for configuring the DSN and sharing it with PDO-based drivers. I highly recommend doing that, as it's what I do in my own [app-skeleton](https://github.com/josegonzalez/app/blob/master/config/.env.default#L22).
