### ISSUE TITLE
Option to set the table name

### ISSUE THREAD

**Issue by narendravaghela** [josegonzalez/cakephp-queuesadilla#30]
Is there any way in a configuration to use a different database table for different queue configuration?

**Comment by angelxmoreno** [comment]
@narendravaghela take a look at https://github.com/josegonzalez/cakephp-queuesadilla/blob/master/src/Queue/Queue.php#L28

```
 *    'url' => 'mysql://username:password@host:port/my-database?table=jobs'
```
looks like it is just a query string called `table`
