### ISSUE TITLE
Queue::push param $callable mixed?

### ISSUE THREAD

**Issue by delamux** [josegonzalez/cakephp-queuesadilla#31]
* [x]  discuss

According with this [documentation](https://github.com/josegonzalez/php-queuesadilla/blob/master/docs/defining-jobs.md#object-instances)

The Queue::push method accepts mixed param, right?

line [279](https://github.com/josegonzalez/cakephp-queuesadilla/blob/master/src/Queue/Queue.php#L279)

**Comment by josegonzalez** [comment]
That is still a callable.
