### ISSUE TITLE
Set flag to disable "Debug: No job!" spam

### ISSUE THREAD

**Issue by FinlayDaG33k** [josegonzalez/cakephp-queuesadilla#34]
Hii there,

I was wondering whether it'd be possible to get rid of the `Debug: No job!` being spammed in the console using some flag.  
My entire console get's spammed (every second one line) and it's pretty annoying when I'm trying to read a message and it just keeps going on...

**Comment by josegonzalez** [comment]
Pull requests welcome.

**Comment by FinlayDaG33k** [comment]
It appears like I need to move this to the `php-queuesadilla` repo instead.
Closing it here.
